============================= test session starts ==============================
platform darwin -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /Users/bopo/workspace/finance/packages/mooquant, inifile:
plugins: pylama-7.4.1, celery-4.1.0
collected 412 items

tests/bar_test.py ........
tests/barfeed_test.py .....
tests/broker_backtesting_test.py .........................................................
tests/broker_test.py ...
tests/btcharts_test.py ...
tests/csvfeed_test.py ....
tests/dataseries_test.py .....F.................
tests/dbfeed_test.py ...
tests/drawdown_analyzer_test.py ..........
tests/eventprofiler_test.py ...
tests/fill_strategy_test.py .....
tests/memfeed_test.py ...
tests/multi_instrument_strategy_test.py ...
tests/observer_test.py ..........
tests/position_test.py ......................................
tests/resample_test.py ................
tests/returns_analyzer_test.py ........................
tests/sharpe_analyzer_test.py ......
tests/slippage_model_test.py .....
tests/smacrossover_strategy_test.py ..
tests/strategy_test.py ...........
tests/talib_test.py ......................F...F..............F...........
tests/technical_atr_test.py ..
tests/technical_bollinger_test.py ..
tests/technical_cross_test.py .........
tests/technical_cumret_test.py .
tests/technical_highlow_test.py .
tests/technical_hurst_test.py ......
tests/technical_linebreak_test.py ...
tests/technical_linreg_test.py ....
tests/technical_ma_test.py ................
tests/technical_macd_test.py .
tests/technical_ratio_test.py ...
tests/technical_roc_test.py ....
tests/technical_rsi_test.py .....
tests/technical_stats_test.py ....
tests/technical_stoch_test.py ....
tests/technical_test.py .
tests/technical_trend_test.py ......
tests/technical_vwap_test.py .......
tests/trades_analyzer_test.py .............
tests/utils_test.py .....F...................

=================================== FAILURES ===================================
____________________ TestSequenceDataSeries.testSeqLikeOps _____________________

self = <tests.dataseries_test.TestSequenceDataSeries testMethod=testSeqLikeOps>

    def testSeqLikeOps(self):
        seq = range(10)
        ds = dataseries.SequenceDataSeries()
    
        for value in seq:
            ds.append(value)
    
        # Test length and every item.
        self.assertEqual(len(ds), len(seq))
    
        for i in range(len(seq)):
            self.assertEqual(ds[i], seq[i])
    
        # Test negative indices
        self.assertEqual(ds[-1], seq[-1])
        self.assertEqual(ds[-2], seq[-2])
        self.assertEqual(ds[-9], seq[-9])
    
        # Test slices
        sl = slice(0, 1, 2)
>       self.assertEqual(ds[sl], seq[sl])
E       AssertionError: [0] != range(0, 1, 2)

tests/dataseries_test.py:82: AssertionError
_______________________________ TestCase.testMA ________________________________

self = <tests.talib_test.TestCase testMethod=testMA>

    def testMA(self):
        barDs = self.__loadBarDS()
        self.assertTrue(compare(indicator.MA(barDs.getCloseDataSeries(), 252, 2, talib.MA_Type.SMA)[1], 93.16))  # Original value 93.15
>       self.assertTrue(compare(indicator.MA(barDs.getCloseDataSeries(), 252, 2, talib.MA_Type.SMA)[2], 94.59))
E       AssertionError: False is not true

tests/talib_test.py:363: AssertionError
_______________________________ TestCase.testMAX _______________________________

self = <tests.talib_test.TestCase testMethod=testMAX>

    def testMAX(self):
        barDs = self.__loadBarDS()
>       self.assertTrue(compare(indicator.MAX(barDs.getOpenDataSeries(), 252, 14)[13], 98.815))
E       AssertionError: False is not true

tests/talib_test.py:389: AssertionError
_______________________________ TestCase.testSMA _______________________________

self = <tests.talib_test.TestCase testMethod=testSMA>

    def testSMA(self):
        barDs = self.__loadBarDS()
        self.assertTrue(compare(indicator.SMA(barDs.getCloseDataSeries(), 252, 2)[1], 93.16))  # Original value 93.15
>       self.assertTrue(compare(indicator.SMA(barDs.getCloseDataSeries(), 252, 2)[2], 94.59))
E       AssertionError: False is not true

tests/talib_test.py:488: AssertionError
_____________ IntersectTestCase.testFullIntersectionWithDateTimes ______________

self = <tests.utils_test.IntersectTestCase testMethod=testFullIntersectionWithDateTimes>

    def testFullIntersectionWithDateTimes(self):
        size = 1000
        dateTimes1 = []
        dateTimes2 = []
        now = datetime.datetime.now()
        for i in range(size):
            dateTimes1.append(now + datetime.timedelta(seconds=i))
            dateTimes2.append(now + datetime.timedelta(seconds=i))
    
        self.assertEqual(dateTimes1, dateTimes2)
    
        values, ix1, ix2 = collections.intersect(dateTimes1, dateTimes2)
        self.assertEqual(values, dateTimes1)
        self.assertEqual(values, dateTimes2)
>       self.assertEqual(ix1, range(size))
E       AssertionError: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12[4844 chars] 999] != range(0, 1000)

tests/utils_test.py:181: AssertionError
=============================== warnings summary ===============================
tests/drawdown_analyzer_test.py::TestBarFeed
  cannot collect test class 'TestBarFeed' because it has a __init__ constructor

tests/position_test.py::TestBarFeed
  cannot collect test class 'TestBarFeed' because it has a __init__ constructor

tests/position_test.py::TestStrategy
  cannot collect test class 'TestStrategy' because it has a __init__ constructor

tests/strategy_test.py::TestStrategy
  cannot collect test class 'TestStrategy' because it has a __init__ constructor

tests/technical_test.py::TestEventWindow
  cannot collect test class 'TestEventWindow' because it has a __init__ constructor

tests/technical_test.py::TestFilter
  cannot collect test class 'TestFilter' because it has a __init__ constructor

tests/trades_analyzer_test.py::TradesAnalyzerTestCase::testSomeTrades
  /usr/local/lib/python3.6/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
    keepdims=keepdims)
  /usr/local/lib/python3.6/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in double_scalars
    ret = ret.dtype.type(ret / rcount)

tests/trades_analyzer_test.py::TradesAnalyzerTestCase::testSomeTrades_Position
  /usr/local/lib/python3.6/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
    keepdims=keepdims)
  /usr/local/lib/python3.6/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in double_scalars
    ret = ret.dtype.type(ret / rcount)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
============== 5 failed, 407 passed, 10 warnings in 39.83 seconds ==============
